/* =============================================================================
   QUERIES DE EXPORTACIÓN — AUTOCONTENIDAS (no requieren crear vistas)
   BD legavcl_caitan · MySQL 5.7 · IDs de estado confirmados en producción:
       1 = En Revisión · 2 = Acreditado · 3,4,5 = rechazos
   Ejecutar cada una por separado y exportar a CSV (UTF-8, coma, con cabecera).
   ============================================================================= */

/* ---------- CSV 1 · acred_casos.csv — una fila por trabajador-contrato ------- */
SELECT
    asg.ID_ASIGNACION,
    per.RUT                                          AS RUT_TRABAJADOR,
    TRIM(CONCAT_WS(' ', per.NOMBRE, per.APELLIDO))   AS TRABAJADOR,
    per.CARGO,
    COALESCE(emp.NOMBRE_FANTASIA, emp.NOMBRE)        AS EMPRESA,
    man.NOMBRE_FAENA                                 AS MANDANTE,
    ger.DESCRIPCION                                  AS GERENCIA,
    con.NUMERO_ACUERDO,
    asg.FECHA_REGISTRO                               AS FECHA_ASIGNACION,
    sol.F_PRIMERA_SOLICITUD,
    sol.F_ULTIMA_SOLICITUD,
    sol.N_SOLICITUDES,
    ap.F_APROBACION,
    COALESCE(rz.N_RECHAZOS, 0)                       AS N_RECHAZOS,
    ult.ESTADO_ACTUAL,
    ult.F_ULTIMO_ESTADO,
    CASE WHEN ap.F_APROBACION IS NULL THEN 'ABIERTO' ELSE 'CERRADO' END AS ESTADO_CASO,
    ROUND(TIMESTAMPDIFF(HOUR, asg.FECHA_REGISTRO,     sol.F_PRIMERA_SOLICITUD)/24, 2) AS DIAS_PREPARACION,
    ROUND(TIMESTAMPDIFF(HOUR, sol.F_PRIMERA_SOLICITUD, ap.F_APROBACION)/24, 2)        AS DIAS_TOTAL,
    ROUND(TIMESTAMPDIFF(HOUR, sol.F_ULTIMA_SOLICITUD,  ap.F_APROBACION)/24, 2)        AS DIAS_ULTIMO_ENVIO,
    ROUND(cic.HORAS_MANDANTE/24, 2)                                                   AS DIAS_EN_MANDANTE,
    ROUND((TIMESTAMPDIFF(HOUR, sol.F_PRIMERA_SOLICITUD, ap.F_APROBACION) - cic.HORAS_MANDANTE)/24, 2) AS DIAS_EN_CONTRATISTA,
    ROUND(TIMESTAMPDIFF(HOUR, sol.F_PRIMERA_SOLICITUD, NOW())/24, 0)                  AS DIAS_ANTIGUEDAD,
    DATE_FORMAT(sol.F_PRIMERA_SOLICITUD, '%Y-%m')    AS MES_SOLICITUD,
    DATE_FORMAT(ap.F_APROBACION, '%Y-%m')            AS MES_APROBACION
FROM DB_LEGAV_ASIG_PERSONAL_ACUERDO asg
JOIN (
    SELECT ID_ASIGNACION, MIN(FECHA_REGISTRO) AS F_PRIMERA_SOLICITUD,
           MAX(FECHA_REGISTRO) AS F_ULTIMA_SOLICITUD, COUNT(*) AS N_SOLICITUDES
    FROM DB_LEGAV_SOLICITUD_ACREDITACION
    WHERE FECHA_REGISTRO IS NOT NULL GROUP BY ID_ASIGNACION
) sol ON sol.ID_ASIGNACION = asg.ID_ASIGNACION
LEFT JOIN DB_LEGAV_PERSONAL_ACREDITACION per ON per.ID_PERSONA      = asg.ID_PERSONA
LEFT JOIN DB_LEGAV_CONTRATO_EMP          con ON con.ID_REG_CONTRATO = asg.ID_REG_ACUERDOS
LEFT JOIN DB_LEGAV_EMPRESA               emp ON emp.ID_EMPRESA      = COALESCE(con.ID_EMPRESA, per.ID_EMPRESA)
LEFT JOIN DB_LEGAV_MANDANTE              man ON man.ID_MANDANTE     = con.ID_MANDANTE
LEFT JOIN DB_LEGAV_MAN_GERENCIA_DETALLE  gd  ON gd.ID_DETALLE_GERENCIA = con.ID_DETALLE_GERENCIA
LEFT JOIN DB_LEGAV_MANDANTE_GERENCIA     ger ON ger.ID_GERENCIA     = gd.ID_GERENCIA
LEFT JOIN (
    SELECT ID_ASIGNACION, MIN(FECHA_REGISTRO) AS F_APROBACION
    FROM DB_LEGAV_STATUS_ACREDITACION_PERSONA
    WHERE ID_ESTADO_ACREDITACION = 2 GROUP BY ID_ASIGNACION
) ap ON ap.ID_ASIGNACION = asg.ID_ASIGNACION
LEFT JOIN (
    SELECT ID_ASIGNACION, COUNT(*) AS N_RECHAZOS
    FROM DB_LEGAV_STATUS_ACREDITACION_PERSONA
    WHERE ID_ESTADO_ACREDITACION IN (3,4,5) GROUP BY ID_ASIGNACION
) rz ON rz.ID_ASIGNACION = asg.ID_ASIGNACION
LEFT JOIN (
    SELECT s.ID_ASIGNACION,
           SUM(TIMESTAMPDIFF(HOUR, s.FECHA_REGISTRO, e.FECHA_REGISTRO)) AS HORAS_MANDANTE
    FROM DB_LEGAV_SOLICITUD_ACREDITACION s
    JOIN DB_LEGAV_STATUS_ACREDITACION_PERSONA e ON e.ID_ESTATUS = (
        SELECT MIN(e2.ID_ESTATUS) FROM DB_LEGAV_STATUS_ACREDITACION_PERSONA e2
        WHERE e2.ID_ASIGNACION = s.ID_ASIGNACION
          AND e2.FECHA_REGISTRO >= s.FECHA_REGISTRO
          AND e2.ID_ESTADO_ACREDITACION IN (2,3,4,5))
    WHERE s.FECHA_REGISTRO IS NOT NULL GROUP BY s.ID_ASIGNACION
) cic ON cic.ID_ASIGNACION = asg.ID_ASIGNACION
LEFT JOIN (
    SELECT e.ID_ASIGNACION, c.DESCRIPCION AS ESTADO_ACTUAL, e.FECHA_REGISTRO AS F_ULTIMO_ESTADO
    FROM DB_LEGAV_STATUS_ACREDITACION_PERSONA e
    JOIN DB_LEGAV_ESTATUS_ACREDITACION c ON c.ID_ESTADO_ACREDITACION = e.ID_ESTADO_ACREDITACION
    JOIN (SELECT ID_ASIGNACION, MAX(ID_ESTATUS) AS ID_ESTATUS
          FROM DB_LEGAV_STATUS_ACREDITACION_PERSONA GROUP BY ID_ASIGNACION) m
      ON m.ID_ESTATUS = e.ID_ESTATUS
) ult ON ult.ID_ASIGNACION = asg.ID_ASIGNACION
ORDER BY sol.F_PRIMERA_SOLICITUD;


/* ---------- CSV 2 · acred_ciclos.csv — una fila por envío a revisión -------- */
SELECT
    sol.ID_SOLICITUD,
    sol.ID_ASIGNACION,
    (SELECT COUNT(*) FROM DB_LEGAV_SOLICITUD_ACREDITACION s2
      WHERE s2.ID_ASIGNACION = sol.ID_ASIGNACION
        AND s2.FECHA_REGISTRO <= sol.FECHA_REGISTRO)  AS NRO_CICLO,
    per.RUT                                           AS RUT_TRABAJADOR,
    COALESCE(emp.NOMBRE_FANTASIA, emp.NOMBRE)         AS EMPRESA,
    man.NOMBRE_FAENA                                  AS MANDANTE,
    con.NUMERO_ACUERDO,
    sol.FECHA_REGISTRO                                AS FECHA_SOLICITUD,
    rev.FECHA_REGISTRO                                AS FECHA_EN_REVISION,
    est.FECHA_REGISTRO                                AS FECHA_DESENLACE,
    cat.DESCRIPCION                                   AS ESTADO_DESENLACE,
    CASE WHEN est.ID_ESTADO_ACREDITACION = 2 THEN 'APROBADO'
         WHEN est.ID_ESTADO_ACREDITACION IN (3,4,5) THEN 'RECHAZADO' END AS RESULTADO_CICLO,
    TRIM(CONCAT_WS(' ', adm.NOMBRE, adm.APELLIDO))    AS REVISOR,
    doc.NOMBRE                                        AS DOCUMENTO_BLOQUEO,
    est.OBSERVACION                                   AS OBS_DESENLACE,
    ROUND(TIMESTAMPDIFF(HOUR, sol.FECHA_REGISTRO, est.FECHA_REGISTRO)/24, 2) AS DIAS_CICLO,
    ROUND(TIMESTAMPDIFF(HOUR, sol.FECHA_REGISTRO, rev.FECHA_REGISTRO)/24, 2) AS DIAS_EN_COLA,
    ROUND(TIMESTAMPDIFF(HOUR, rev.FECHA_REGISTRO, est.FECHA_REGISTRO)/24, 2) AS DIAS_TRABAJO_EFECTIVO,
    DATE_FORMAT(sol.FECHA_REGISTRO, '%Y-%m')          AS MES_SOLICITUD,
    DAYNAME(sol.FECHA_REGISTRO)                       AS DIA_SEMANA,
    HOUR(sol.FECHA_REGISTRO)                          AS HORA_SOLICITUD
FROM DB_LEGAV_SOLICITUD_ACREDITACION sol
JOIN      DB_LEGAV_ASIG_PERSONAL_ACUERDO asg ON asg.ID_ASIGNACION   = sol.ID_ASIGNACION
LEFT JOIN DB_LEGAV_PERSONAL_ACREDITACION per ON per.ID_PERSONA      = asg.ID_PERSONA
LEFT JOIN DB_LEGAV_CONTRATO_EMP          con ON con.ID_REG_CONTRATO = asg.ID_REG_ACUERDOS
LEFT JOIN DB_LEGAV_EMPRESA               emp ON emp.ID_EMPRESA      = COALESCE(con.ID_EMPRESA, per.ID_EMPRESA)
LEFT JOIN DB_LEGAV_MANDANTE              man ON man.ID_MANDANTE     = con.ID_MANDANTE
LEFT JOIN (
    SELECT s.ID_SOLICITUD, MIN(e.ID_ESTATUS) AS ID_DES
    FROM DB_LEGAV_SOLICITUD_ACREDITACION s
    JOIN DB_LEGAV_STATUS_ACREDITACION_PERSONA e
      ON e.ID_ASIGNACION = s.ID_ASIGNACION AND e.FECHA_REGISTRO >= s.FECHA_REGISTRO
     AND e.ID_ESTADO_ACREDITACION IN (2,3,4,5)
    WHERE s.FECHA_REGISTRO IS NOT NULL GROUP BY s.ID_SOLICITUD
) d ON d.ID_SOLICITUD = sol.ID_SOLICITUD
LEFT JOIN DB_LEGAV_STATUS_ACREDITACION_PERSONA est ON est.ID_ESTATUS = d.ID_DES
LEFT JOIN (
    SELECT s.ID_SOLICITUD, MIN(e.ID_ESTATUS) AS ID_REV
    FROM DB_LEGAV_SOLICITUD_ACREDITACION s
    JOIN DB_LEGAV_STATUS_ACREDITACION_PERSONA e
      ON e.ID_ASIGNACION = s.ID_ASIGNACION AND e.FECHA_REGISTRO >= s.FECHA_REGISTRO
     AND e.ID_ESTADO_ACREDITACION = 1
    WHERE s.FECHA_REGISTRO IS NOT NULL GROUP BY s.ID_SOLICITUD
) r ON r.ID_SOLICITUD = sol.ID_SOLICITUD
LEFT JOIN DB_LEGAV_STATUS_ACREDITACION_PERSONA rev
       ON rev.ID_ESTATUS = r.ID_REV AND (d.ID_DES IS NULL OR rev.ID_ESTATUS < d.ID_DES)
LEFT JOIN DB_LEGAV_ESTATUS_ACREDITACION      cat ON cat.ID_ESTADO_ACREDITACION = est.ID_ESTADO_ACREDITACION
LEFT JOIN DB_LEGAV_ADMINISTRATIVOS           adm ON adm.ID_USU_LEGAV = est.ID_USU_LEGAV
LEFT JOIN DB_DOCUMENTO_ESTANDAR_ACREDITACION doc ON doc.ID_DOCUMENTO = est.ID_DOCUMENTO_BLOQUEO
WHERE sol.FECHA_REGISTRO IS NOT NULL
ORDER BY sol.ID_ASIGNACION, NRO_CICLO;
